version: '3.7'

services:

  mysql:
    image: mysql:8
    ports:
      - $MYSQL_TCP_PORT:3306
    command:
      - --default_authentication_plugin=mysql_native_password
      - --transaction_isolation=READ-COMMITTED
      - --character_set_server=utf8mb4
      - --collation_server=utf8mb4_bin
      - --local-infile=1
      - --innodb_flush_method=nosync
      - --innodb_flush_log_at_trx_commit=0
      - --gtid_mode=ON
      - --enforce_gtid_consistency=ON
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ~
      MYSQL_USER: ~
      MYSQL_PASSWORD: ~
